"""Liste exhaustive de modeles VTT enduro/AM/trail/DH/freeride pour le filtrage
cote Python apres fetch LBC. Genere via Claude Opus le 2026-04-29.

Si un titre/body LBC contient un de ces termes (apres normalisation : lowercase,
sans accents, ponctuation -> espaces), l'annonce est consideree pertinente.
Les termes DH ont priorite sur enduro pour la categorisation.
"""

# Mots-cles generiques qui qualifient enduro/trail/AM
GENERIC_ENDURO = {
    'all mountain',
    'allmountain',
    'endurigide',
    'enduro',
    'freeride',
    'hardtail enduro',
    'trail',
}

# Mots-cles generiques qui qualifient DH/descente
GENERIC_DH = {
    'bike park',
    'descente',
    'dh',
    'downhill',
    'park bike',
    'slopestyle',
}

# Marques 100% MTB enduro/DH (matchent meme seules dans le titre)
BRANDS_ENDURO_PURE = {
    'banshee',
    'commencal',
    'cotic',
    'devinci',
    'evil',
    'evil bikes',
    'forbidden',
    'geometron',
    'guerrilla gravity',
    'ibis',
    'ibis cycles',
    'knolly',
    'last bikes',
    'mondraker',
    'nukeproof',
    'pivot',
    'pivot cycles',
    'pole',
    'pole bicycles',
    'privateer',
    'production privee',
    'propain',
    'raaw',
    'saracen',
    'stanton',
    'starling',
    'transition',
    'transition bikes',
    'yt',
    'yt industries',
}

ENDURO_TERMS = {
    # Modeles VTT enfants enduro/AM/trail (marques specialisees kids)
    'spawn yoji', 'spawn reaper', 'spawn savage', 'spawn yama jama',
    'spawn furi', 'spawn banshee',
    'early rider hellion', 'early rider trail rider', 'early rider hellion 24',
    'early rider hellion 26',
    'frog mtb', 'frog 60', 'frog 62', 'frog 69', 'frog 72', 'frog 78',
    'vpace max26', 'vpace max275', 'vpace max24', 'vpace max20',
    'commencal ramones', 'commencal absolut',
    'lemonyellow', 'cleary scout',
    # Originals
    '160e c-series',
    '160e t-series',
    'aeris',
    'aether',
    'allmtn',
    'allmtn cf sl',
    'alltrail',
    'alpine trail',
    'alpine trail e',
    'altitude',
    'altitude powerplay',
    'altitude powerplay carbon 90',
    'am e',
    'amflow pl carbon',
    'amflow pl pro',
    'ams hybrid one44',
    'analog',
    'ariel',
    'ariel e',
    'ariel lsd',
    'arrival e',
    'aspect eride',
    'atherton am e',
    'atom-x',
    'atomx',
    'attention',
    'atx 01',
    'banshee paradox',
    'banshee phantom',
    'banshee prime',
    'banshee rune',
    'banshee spitfire',
    'banshee titan',
    'beast of the east',
    'bergamont contrail',
    'bergamont e-contrail',
    'bergamont e-horizon',
    'bergamont e-revox',
    'bergamont e-trailster',
    'bergamont encore',
    'bergamont revox',
    'bergamont trailster',
    'berria mako hybrid',
    'bh atom',
    'bh atom-x',
    'bh atomx',
    'bh ilynx enduro',
    'bh ilynx race',
    'bh ilynx trail',
    'bh ilynx+',
    'bh lynx 5',
    'bh lynx 6',
    'bh lynx trail',
    'bh x-tep',
    'bianchi e-omnia fs',
    'bianchi e-omnia t',
    'bianchi t-tronik performer',
    'bianchi t-tronik rebel',
    'big honzo',
    'big trail',
    'bigfoot vlt',
    'bird aeris',
    'bird aether',
    'bird eaeris',
    'bird zero',
    'blizzard',
    'blur tr',
    'bmc amp',
    'bmc blast',
    'bmc fourstroke amp',
    'bmc fourstroke lt',
    'bmc speedfox',
    'bmc speedfox amp',
    'bmc trailfox',
    'bmc trailfox amp',
    'bobcat trail',
    'bobcat trail e',
    'bold linkin trail',
    'boost',
    'bronson',
    'bullit',
    'bulls copperhead evo',
    'bulls e-stream evo am',
    'bulls e-stream evo en',
    'bulls sonic evo am',
    'bulls sonic evo am4',
    'bulls sonic evo en',
    'bulls sonic evo tr',
    'cache',
    'camber',
    'cannondale beast of the east',
    'cannondale cujo',
    'cannondale habit',
    'cannondale habit neo',
    'cannondale habit neo 3',
    'cannondale habit neo 4',
    'cannondale jekyll',
    'cannondale moterra',
    'cannondale moterra neo',
    'cannondale trail',
    'cannondale trail neo',
    'cannondale trigger',
    'canyon grand canyon',
    'canyon grand canyon on',
    'canyon neuron',
    'canyon neuron on',
    'canyon spectral',
    'canyon spectral on',
    'canyon spectral on cfr ltd',
    'canyon spectral onfly',
    'canyon stoic',
    'canyon strive',
    'canyon strive on',
    'canyon torque',
    'canyon torque on',
    'capra',
    'centurion lhasa e',
    'centurion no pogo',
    'chainsaw',
    'chameleon',
    'charger',
    'chaser',
    'chilcotin',
    'chisel',
    'chrono',
    'cinder cone',
    'cinto',
    'cipollini mistral e',
    'commencal meta',
    'commencal meta ht',
    'commencal meta power',
    'commencal meta power 27',
    'commencal meta power 29',
    'commencal meta power sx',
    'commencal meta power tr',
    'commencal meta power tr signature',
    'commencal meta tr ohlins',
    'commencal ramones',
    'conor wrc e-trail',
    'contrail',
    'conway emr',
    'conway ewme',
    'conway ryvon',
    'conway xyron',
    'copperhead evo',
    'corratec e-power mtc',
    'corratec e-power rs',
    'cotic bfe',
    'cotic droplink',
    'cotic flaremax',
    'cotic jeht',
    'cotic rocket',
    'cotic rocketmax',
    'cotic solaris',
    'cotic soul',
    'crafty',
    'crave al',
    'cresta emtb',
    'crossmax e',
    'cube ams',
    'cube ams hybrid one44',
    'cube analog',
    'cube attention',
    'cube reaction',
    'cube reaction hybrid',
    'cube stereo',
    'cube stereo hybrid 120',
    'cube stereo hybrid 140',
    'cube stereo hybrid 140 hpc actionteam',
    'cube stereo hybrid 160',
    'cube stereo hybrid 160 sl',
    'cube stereo hybrid one44',
    'cube stereo hybrid slx',
    'decoy',
    'decoy core',
    'decoy sn',
    'delite mountain',
    'devinci ac',
    'devinci chainsaw',
    'devinci django',
    'devinci e-spartan',
    'devinci e-spartan carbon',
    'devinci e-troy',
    'devinci kobain',
    'devinci marshall',
    'devinci spartan',
    'devinci troy',
    'dew-e',
    'digger',
    'django',
    'dji avinox amflow pl carbon',
    'dji avinox amflow pl pro',
    'dmr sled e',
    'dreadnought',
    'drift e',
    'droplink',
    'druid',
    'druid e',
    'e-130',
    'e-150',
    'e-150 rs',
    'e-161',
    'e-180',
    'e-180 rs',
    'e-765',
    'e-asx',
    'e-caliber',
    'e-contrail',
    'e-escarpe',
    'e-horizon',
    'e-hybride',
    'e-inception',
    'e-jaroon',
    'e-kato',
    'e-lyte',
    'e-mythique',
    'e-omnia fs',
    'e-omnia t',
    'e-pordoi',
    'e-power mtc',
    'e-power rs',
    'e-prime',
    'e-revox',
    'e-riot',
    'e-riot enduro',
    'e-riot trail',
    'e-sentier',
    'e-sommet',
    'e-sommet vrx',
    'e-spartan',
    'e-spartan carbon',
    'e-storm',
    'e-stream evo am',
    'e-stream evo en',
    'e-teru',
    'e-trailster',
    'e-troy',
    'e-vantage',
    'e803 trail',
    'e803 trb',
    'e903 all-mountain',
    'eaeris',
    'ebig nine',
    'ebig seven',
    'ebig trail',
    'eforce',
    'ekano',
    'ekano 2',
    'el roy',
    'element',
    'element powerplay',
    'embolden e+',
    'encore',
    'endorphin',
    'enduro',
    'eone-forty',
    'eone-sixty',
    'eone-sixty 10k',
    'eone-sixty 9000',
    'eone-twenty',
    'escarpe',
    'eunduro',
    'everb',
    'evil the calling',
    'evil the epocalypse',
    'evil the following',
    'evil the insurgent',
    'evil the offering',
    'evil the wreckoning',
    'evolink',
    'extreme cross',
    'ezesty',
    'ezesty am ltd ultimate',
    'factor',
    'fathom',
    'fathom e+',
    'firebird',
    'flaremax',
    'fluid fs',
    'fluid ht',
    'fluid vlt',
    'focus jam2',
    'focus jam2 sl 9 9',
    'focus sam2',
    'focus sam2 6 9',
    'focus thron2',
    'forbidden dreadnought',
    'forbidden druid',
    'forbidden druid e',
    'forbidden supernought',
    'force amp',
    'forestal cyon',
    'forestal hydra',
    'forestal siryon',
    'fourstroke amp',
    'fourstroke lt',
    'foxy carbon rr e',
    'foxy r',
    'froggy',
    'fuel ex',
    'fuel exe',
    'fugitive',
    'fullnine',
    'fullseven',
    'g-150',
    'g-160',
    'g1 e',
    'game 8',
    'game 9',
    'genius eride',
    'genius eride 900 tuned',
    'geometron g1',
    'geometron g1 e',
    'geometron g16',
    'ghost e-asx',
    'ghost e-hybride',
    'ghost e-kato',
    'ghost e-riot',
    'ghost e-riot enduro',
    'ghost e-riot trail',
    'ghost e-teru',
    'giant fathom',
    'giant fathom e+',
    'giant reign',
    'giant reign e+',
    'giant reign e+ pro',
    'giant stance',
    'giant stance e+',
    'giant talon',
    'giant talon e+',
    'giant trance',
    'giant trance x advanced e+',
    'giant trance x e+',
    'giant xtc',
    'gnarvana',
    'grand canyon',
    'grand canyon on',
    'greyp g6',
    'growler',
    'gt eforce',
    'gt everb',
    'gt force amp',
    'gt pantera',
    'gt sensor',
    'gt verb',
    'guerrilla gravity gnarvana',
    'guerrilla gravity megatrail',
    'guerrilla gravity pedalhead',
    'guerrilla gravity shred dogg',
    'guerrilla gravity smash',
    'guerrilla gravity trail pistol',
    'habit',
    'habit neo',
    'habit neo 3',
    'habit neo 4',
    'haibike allmtn',
    'haibike allmtn cf sl',
    'haibike alltrail',
    'haibike fullnine',
    'haibike fullseven',
    'haibike lyke',
    'haibike nduro',
    'haibike sduro allmtn',
    'haibike sduro hardnine',
    'haibike sduro hardseven',
    'haibike xduro allmtn',
    'haibike xduro nduro',
    'hard cross',
    'hard cross hc9',
    'hawk hill',
    'heckler',
    'heckler 9',
    'heckler mx',
    'heckler sl',
    'hightower',
    'honzo',
    'hugene',
    'husqvarna extreme cross',
    'husqvarna hard cross',
    'husqvarna hard cross hc9',
    'husqvarna light cross',
    'husqvarna mountain cross',
    'husqvarna mountain cross mc4',
    'hydra',
    'ibis dv9',
    'ibis mojo',
    'ibis oso',
    'ibis oso gx',
    'ibis oso xt',
    'ibis ripley',
    'ibis ripmo',
    'identiti krisis',
    'identiti mettle',
    'ilynx enduro',
    'ilynx race',
    'ilynx trail',
    'ilynx+',
    'instigator',
    'instinct',
    'instinct powerplay',
    'intense tazer mx',
    'intense tazer pro',
    'intrigue x e+',
    'jam2 sl 9 9',
    'jeffsy',
    'jekyll',
    'karate monkey',
    'kenevo',
    'kern e',
    'kern en',
    'kili flyer',
    'knolly cache',
    'knolly chilcotin',
    'knolly endorphin',
    'knolly fugitive',
    'knolly tyaughton',
    'knolly warden',
    'kobain',
    'kona big honzo',
    'kona cinder cone',
    'kona dew-e',
    'kona honzo',
    'kona process',
    'kona remote',
    'kona remote 130',
    'kona remote 160',
    'kona remote ctrl',
    'kona satori',
    'kona unit',
    'krampus',
    'krisis',
    'ktm macina aera',
    'ktm macina chacana',
    'ktm macina kapoho',
    'ktm macina kapoho master',
    'ktm macina lycan',
    'ktm macina mighty',
    'ktm macina prowler',
    'ktm macina prowler exonic',
    'lapierre edge',
    'lapierre ezesty',
    'lapierre ezesty am ltd ultimate',
    'lapierre froggy',
    'lapierre overvolt',
    'lapierre overvolt am',
    'lapierre overvolt fs',
    'lapierre overvolt glp',
    'lapierre overvolt ht',
    'lapierre overvolt tr',
    'lapierre prorace',
    'lapierre spicy',
    'lapierre zesty',
    'last bikes cinto',
    'last bikes coal',
    'last bikes glen',
    'last bikes herb',
    'last bikes tarvo',
    'laufey',
    'lectric lectric xp',
    'lectric xp',
    'lhasa e',
    'light cross',
    'lightrider e',
    'linkin trail',
    'liv embolden e+',
    'liv intrigue x e+',
    'look e-765',
    'lowside',
    'lumen eride',
    'lupine zx1',
    'lynx 5',
    'lynx 6',
    'lynx trail',
    'mach 4 sl',
    'mach 5 5',
    'mach 6',
    'machine',
    'macina aera',
    'macina chacana',
    'macina kapoho',
    'macina kapoho master',
    'macina lycan',
    'macina mighty',
    'macina prowler',
    'macina prowler exonic',
    'madonna',
    'madonna e',
    'mako hybrid',
    'mantra',
    'marin alpine trail',
    'marin alpine trail e',
    'marin bobcat trail',
    'marin bobcat trail e',
    'marin el roy',
    'marin hawk hill',
    'marin pine mountain',
    'marin rift zone',
    'marin rift zone e',
    'marin san quentin',
    'marin wolf ridge',
    'marshall',
    'mavic crossmax e',
    'maxxis spark',
    'mayhem',
    'megamo crave al',
    'megamo ridon',
    'megatower',
    'megatrail',
    'megawatt',
    'megawatt 297 factory',
    'merida big trail',
    'merida ebig nine',
    'merida ebig seven',
    'merida ebig trail',
    'merida eone-forty',
    'merida eone-sixty',
    'merida eone-sixty 10k',
    'merida eone-sixty 9000',
    'merida eone-twenty',
    'merida one-forty',
    'merida one-sixty',
    'merida one-twenty',
    'meta ht',
    'meta power',
    'meta power 27',
    'meta power 29',
    'meta power sx',
    'meta power tr',
    'meta power tr signature',
    'meta tr ohlins',
    'mettle',
    'mistral e',
    'mondraker chaser',
    'mondraker chrono',
    'mondraker crafty',
    'mondraker dune',
    'mondraker dusk',
    'mondraker e-prime',
    'mondraker e-vantage',
    'mondraker factor',
    'mondraker foxy',
    'mondraker foxy carbon rr e',
    'mondraker foxy r',
    'mondraker level',
    'mondraker neat',
    'mondraker prime',
    'mondraker raze',
    'mondraker superfoxy',
    'moterra',
    'moterra neo',
    'mountain cross',
    'mountain cross mc4',
    'moustache game 8',
    'moustache game 9',
    'moustache samedi 27 game',
    'moustache samedi 27 trail',
    'moustache samedi 27 wide',
    'moustache samedi 27 xroad',
    'moustache samedi 29 game',
    'moustache samedi 29 trail',
    'moustache samedi off 6',
    'mt bromo',
    'murmur',
    'murmur e',
    'mythique',
    'nduro',
    'neuron',
    'neuron on',
    'no pogo',
    'nomad',
    'norco bigfoot vlt',
    'norco fluid fs',
    'norco fluid ht',
    'norco fluid vlt',
    'norco optic',
    'norco optic vlt',
    'norco range',
    'norco range vlt',
    'norco range vlt c1',
    'norco sight',
    'norco sight vlt',
    'norco sight vlt c1',
    'norco torrent',
    'nucleus',
    'nukeproof digger',
    'nukeproof giga',
    'nukeproof mega',
    'nukeproof megawatt',
    'nukeproof megawatt 297 factory',
    'nukeproof reactor',
    'nukeproof reactor 290 wt',
    'nukeproof scout',
    'nytro',
    'occam',
    'olympia performer evo',
    'one-forty',
    'one-sixty',
    'one-twenty',
    'optic',
    'optic vlt',
    'orbea laufey',
    'orbea occam',
    'orbea oiz',
    'orbea rallon',
    'orbea rise',
    'orbea rise lt',
    'orbea wild',
    'orbea wild fs',
    'orbea wild ht',
    'orbea wild m-ltd',
    'orbea wild m-team',
    'oso gx',
    'oso xt',
    'overvolt',
    'overvolt am',
    'overvolt fs',
    'overvolt glp',
    'overvolt ht',
    'overvolt tr',
    'pantera',
    'paradox',
    'patrol',
    'patron eride',
    'patron eride 900 tuned',
    'pedalhead',
    'performer evo',
    'phantom',
    'pinarello nytro',
    'pine mountain',
    'pipeline',
    'pitch',
    'pivot firebird',
    'pivot les',
    'pivot mach 4 sl',
    'pivot mach 5 5',
    'pivot mach 6',
    'pivot shuttle',
    'pivot shuttle 140 sl',
    'pivot shuttle am',
    'pivot shuttle lt',
    'pivot shuttle lt 29',
    'pivot shuttle lt pro',
    'pivot shuttle sl',
    'pivot switchblade',
    'pivot trail 429',
    'pole evolink',
    'pole machine',
    'pole stamina e',
    'pole taival',
    'pole voima',
    'polygon mt bromo',
    'polygon premier',
    'polygon siskiu n',
    'polygon siskiu t',
    'polygon square one',
    'polygon xquarone',
    'powerfly fs',
    'powerfly lt',
    'premier',
    'prime',
    'privateer 141',
    'privateer 161',
    'privateer e-161',
    'privateer eunduro',
    'privateer gen',
    'process',
    'production privee frir',
    'production privee oka',
    'production privee shan',
    'propain ekano',
    'propain ekano 2',
    'propain hugene',
    'propain spindrift',
    'propain sresh',
    'propain sresh cf',
    'propain tyee',
    'prorace',
    'r e375',
    'r e750',
    'r x1000',
    'r x375',
    'r x750',
    'raaw jibb',
    'raaw madonna',
    'raaw madonna e',
    'raaw yalla',
    'rallon',
    'ramones',
    'range',
    'range vlt',
    'range vlt c1',
    'ransom',
    'ransom eride',
    'rapcon pmax',
    'rapide',
    'rascal',
    'reaction',
    'reaction hybrid',
    'reactor',
    'reactor 290 wt',
    'reign e+',
    'reign e+ pro',
    'relay',
    'remedy',
    'remote 130',
    'remote 160',
    'remote ctrl',
    'repeater',
    'revel rascal',
    'revox',
    'ridon',
    'riese m ller delite mountain',
    'riese m ller superdelite mountain',
    'rift zone',
    'rift zone e',
    'ripley',
    'ripmo',
    'rise lt',
    'rocket',
    'rocketmax',
    'rocky mountain altitude',
    'rocky mountain altitude powerplay',
    'rocky mountain altitude powerplay carbon 90',
    'rocky mountain blizzard',
    'rocky mountain element',
    'rocky mountain element powerplay',
    'rocky mountain growler',
    'rocky mountain instinct',
    'rocky mountain instinct powerplay',
    'rocky mountain pipeline',
    'rocky mountain slayer',
    'rocky mountain slayer powerplay',
    'rocky mountain soul',
    'roost',
    'root miller',
    'roscoe',
    'rose root miller',
    'rose soul fire',
    'rotwild r e375',
    'rotwild r e750',
    'rotwild r x1000',
    'rotwild r x375',
    'rotwild r x750',
    'ryvon',
    'sam2 6 9',
    'samedi 27 game',
    'samedi 27 trail',
    'samedi 27 wide',
    'samedi 27 xroad',
    'samedi 29 game',
    'samedi 29 trail',
    'samedi off 6',
    'san quentin',
    'santa cruz 5010',
    'santa cruz blur tr',
    'santa cruz bronson',
    'santa cruz bullit',
    'santa cruz chameleon',
    'santa cruz heckler',
    'santa cruz heckler 9',
    'santa cruz heckler mx',
    'santa cruz heckler sl',
    'santa cruz hightower',
    'santa cruz megatower',
    'santa cruz nomad',
    'santa cruz solo',
    'santa cruz tallboy',
    'santa cruz vala',
    'saracen ariel',
    'saracen ariel e',
    'saracen ariel lsd',
    'saracen kili flyer',
    'saracen mantra',
    'saracen zenith',
    'satori',
    'sb120',
    'sb130',
    'sb135',
    'sb140',
    'sb150',
    'sb160',
    'sb165',
    'sb4 5',
    'scale',
    'scott aspect eride',
    'scott genius',
    'scott genius eride',
    'scott genius eride 900 tuned',
    'scott lumen eride',
    'scott patron',
    'scott patron eride',
    'scott patron eride 900 tuned',
    'scott ransom',
    'scott ransom eride',
    'scott scale',
    'scott spark',
    'scott strike eride',
    'scott voltage',
    'scott voltage eride',
    'scout',
    'sduro allmtn',
    'sduro hardnine',
    'sduro hardseven',
    'sensor',
    'sentier',
    'sentinel',
    'shamann',
    'sherco se-mtb',
    'sherco sherco se-mtb',
    'sherpa',
    'sherpa e-mtb',
    'sherpa sherpa e-mtb',
    'sherpa ti',
    'sherpa+',
    'shred dogg',
    'shuttle',
    'shuttle 140 sl',
    'shuttle am',
    'shuttle lt',
    'shuttle lt 29',
    'shuttle lt pro',
    'shuttle sl',
    'sight',
    'sight vlt',
    'sight vlt c1',
    'simplon rapcon pmax',
    'simplon steamer pmax',
    'siryon',
    'siskiu n',
    'siskiu t',
    'slackline',
    'slash',
    'slash 9 9 xx1 axs',
    'slash+',
    'slayer',
    'slayer powerplay',
    'sled e',
    'smash',
    'smuggler',
    'solaris',
    'sommet',
    'sonic evo am',
    'sonic evo am4',
    'sonic evo en',
    'sonic evo tr',
    'soul fire',
    'spartan',
    'specialized camber',
    'specialized chisel',
    'specialized enduro',
    'specialized fuse',
    'specialized kenevo',
    'specialized levo',
    'specialized pitch',
    'specialized stumpjumper',
    'specialized stumpjumper evo',
    'specialized turbo kenevo',
    'specialized turbo kenevo sl',
    'specialized turbo levo',
    'specialized turbo levo alloy',
    'specialized turbo levo comp',
    'specialized turbo levo expert',
    'specialized turbo levo pro',
    'specialized turbo levo s-works',
    'specialized turbo levo sl',
    'specialized turbo tero',
    'spectral',
    'spectral on',
    'spectral on cfr ltd',
    'spectral onfly',
    'speedfox',
    'speedfox amp',
    'spicy',
    'spindrift',
    'spire',
    'spitfire',
    'spot brand mayhem',
    'square one',
    'sresh',
    'sresh cf',
    'stache',
    'stamina e',
    'stance',
    'stance e+',
    'stanton sherpa',
    'stanton sherpa ti',
    'stanton sherpa+',
    'stanton slackline',
    'stanton switch9er',
    'stanton switchback',
    'stark drift e',
    'starling murmur',
    'starling murmur e',
    'starling roost',
    'starling sturn',
    'starling swoop',
    'starling twist',
    'steamer pmax',
    'stereo',
    'stereo hybrid 120',
    'stereo hybrid 140',
    'stereo hybrid 140 hpc actionteam',
    'stereo hybrid 160',
    'stereo hybrid 160 sl',
    'stereo hybrid one44',
    'stereo hybrid slx',
    'stevens e-inception',
    'stevens e-pordoi',
    'stoic',
    'strike eride',
    'strive',
    'strive on',
    'stumpjumper',
    'stumpjumper evo',
    'sturn',
    'sunday e-mtb',
    'sunday sunday e-mtb',
    'sunn charger',
    'sunn kern',
    'sunn kern e',
    'sunn kern en',
    'sunn shamann',
    'superdelite mountain',
    'superfoxy',
    'supernought',
    'surly instigator',
    'surly karate monkey',
    'surly krampus',
    'surly lowside',
    'switch9er',
    'switchback',
    'switchblade',
    'swoop',
    't-130',
    't-140',
    't-160',
    't-tronik performer',
    't-tronik rebel',
    'taival',
    'tallboy',
    'talon',
    'talon e+',
    'tarvo',
    'tazer mx',
    'tazer pro',
    'th mus lightrider e',
    'the calling',
    'the epocalypse',
    'the following',
    'the insurgent',
    'the offering',
    'the wreckoning',
    'thron2',
    'throttle',
    'time atx 01',
    'titan',
    'top fuel',
    'torque',
    'torque on',
    'torrent',
    'trail 429',
    'trail neo',
    'trail pistol',
    'trailfox',
    'trailfox amp',
    'trailster',
    'trance',
    'trance x advanced e+',
    'trance x e+',
    'transition patrol',
    'transition relay',
    'transition repeater',
    'transition scout',
    'transition sentinel',
    'transition smuggler',
    'transition spire',
    'transition throttle',
    'trek e-caliber',
    'trek fuel ex',
    'trek fuel exe',
    'trek powerfly fs',
    'trek powerfly lt',
    'trek rail',
    'trek remedy',
    'trek roscoe',
    'trek slash',
    'trek slash 9 9 xx1 axs',
    'trek slash+',
    'trek stache',
    'trek top fuel',
    'trigger',
    'turbo kenevo',
    'turbo kenevo sl',
    'turbo levo',
    'turbo levo alloy',
    'turbo levo comp',
    'turbo levo expert',
    'turbo levo pro',
    'turbo levo s-works',
    'turbo levo sl',
    'turbo tero',
    'twist',
    'tyaughton',
    'unno boost',
    'unno mith',
    'vitus e-escarpe',
    'vitus e-mythique',
    'vitus e-sentier',
    'vitus e-sommet',
    'vitus e-sommet vrx',
    'vitus escarpe',
    'vitus mythique',
    'vitus nucleus',
    'vitus rapide',
    'vitus sentier',
    'vitus sommet',
    'voima',
    'voltage',
    'voltage eride',
    'wallerang e',
    'wallerang wallerang e',
    'warden',
    'we are one arrival e',
    'whyte 901',
    'whyte 905',
    'whyte 909',
    'whyte e-130',
    'whyte e-150',
    'whyte e-150 rs',
    'whyte e-180',
    'whyte e-180 rs',
    'whyte e-lyte',
    'whyte g-150',
    'whyte g-160',
    'whyte t-130',
    'whyte t-140',
    'whyte t-160',
    'wild fs',
    'wild ht',
    'wild m-ltd',
    'wild m-team',
    'wilier e-jaroon',
    'wilier e-storm',
    'wilier e803 trail',
    'wilier e803 trb',
    'wilier e903 all-mountain',
    'wolf ridge',
    'wrc e-trail',
    'x-tep',
    'xduro allmtn',
    'xduro nduro',
    'xquarone',
    'xyron',
    'yalla',
    'yeti 160e',
    'yeti 160e c-series',
    'yeti 160e t-series',
    'yeti arc',
    'yeti sb120',
    'yeti sb130',
    'yeti sb135',
    'yeti sb140',
    'yeti sb150',
    'yeti sb160',
    'yeti sb165',
    'yeti sb4 5',
    'yeti sb5',
    'yeti sb6',
    'yeti sb66',
    'yeti sb95',
    'yt decoy',
    'yt decoy core',
    'yt decoy sn',
    'yt industries capra',
    'yt industries decoy',
    'yt industries izzo',
    'yt industries jeffsy',
    'zenith',
    'zesty',
}

DH_TERMS = {
    'absolut',
    'aether dh',
    'alcatraz',
    'amplitude',
    'argus',
    'atherton bikes dh',
    'aurum',
    'banshee darkside',
    'banshee legend',
    'banshee wildcard',
    'bergamont big air',
    'bergamont straitline',
    'big air',
    'big hit',
    'bionicon edison',
    'bird aether dh',
    'boot r',
    'bottle rocket',
    'cannondale chase',
    'cannondale claymore',
    'cannondale dave',
    'cannondale judge',
    'cannondale perp',
    'canyon sender',
    'canyon stitched',
    'canyon torque dhx',
    'canyon torque frx',
    'capital',
    'chase',
    'clash',
    'claymore',
    'collosus dh',
    'commencal absolut',
    'commencal clash',
    'commencal furious',
    'commencal meta sx',
    'commencal supreme 29',
    'commencal supreme dh',
    'compulsion',
    'cube flying circus',
    'cube hanzz',
    'cube two15',
    'darkside',
    'decade',
    'delirium',
    'devinci wilson',
    'diamondback mission pro',
    'diamondback scapegoat',
    'dirt love',
    'dissent',
    'distortion',
    'dominer',
    'driver 8',
    'edison',
    'entourage',
    'evil imperial',
    'evil insurgent',
    'evil wreckoning',
    'felt compulsion',
    'flatline',
    'flying circus',
    'foes hydro',
    'foes mixer dh',
    'foreman',
    'furious',
    'gambler',
    'gt distortion',
    'gt force',
    'gt fury',
    'gt la bomba',
    'gt sanction',
    'haibike heet dh',
    'hanzz',
    'heet dh',
    'hydro',
    'identiti aka',
    'identiti p-66',
    'imperial',
    'insurgent',
    'intense 951',
    'intense m16',
    'intense m29',
    'intense m9',
    'intense tazer dh',
    'intense uzzi',
    'ion 20',
    'judge',
    'knolly delirium',
    'knolly podium',
    'kona entourage',
    'kona operator',
    'kona shred',
    'kona stinky',
    'la bomba',
    'lapierre dh',
    'last herb',
    'legend',
    'liteville 601',
    'maiden',
    'majesty',
    'marin alcatraz',
    'marin quake',
    'marin wolf ridge pro',
    'meta sx',
    'metropolis',
    'mission dh',
    'mission pro',
    'mixer dh',
    'mondraker summum',
    'mongoose argus',
    'mongoose boot r',
    'mongoose foreman',
    'movement',
    'nicolai ion 20',
    'norco aurum',
    'norco ryde',
    'norco shore',
    'norco team dh',
    'norco two50',
    'ns bikes capital',
    'ns bikes decade',
    'ns bikes fuzz',
    'ns bikes holy',
    'ns bikes majesty',
    'ns bikes metropolis',
    'ns bikes movement',
    'ns bikes snabb',
    'ns bikes soda',
    'ns bikes suburban',
    'ns bikes surge',
    'nukeproof dissent',
    'nukeproof pulse',
    'nukeproof snap',
    'octane one prone',
    'octane one zircus',
    'operator',
    'orange 322',
    'orange 324',
    'orange 327',
    'orange 329',
    'p slope',
    'phoenix',
    'pivot phoenix',
    'podium',
    'pole stamina',
    'polygon collosus dh',
    'production privee shan g2',
    'prone',
    'propain rage',
    'pulse',
    'quake',
    'rocky mountain flatline',
    'rocky mountain maiden',
    'rocky mountain rmx',
    'rocky mountain slayer ss',
    'sanction',
    'santa cruz driver 8',
    'santa cruz v10',
    'saracen amplitude',
    'saracen myst',
    'scapegoat',
    'scott gambler',
    'scott voltage fr',
    'scott voltage yz',
    'sender',
    'session',
    'shan g2',
    'shred',
    'slayer ss',
    'snabb',
    'solid mission dh',
    'solid strip',
    'specialized big hit',
    'specialized demo',
    'specialized p 2',
    'specialized p 3',
    'specialized p slope',
    'specialized status',
    'specialized sx trail',
    'stamina',
    'status',
    'stinky',
    'stitched',
    'straitline',
    'strip',
    'suburban',
    'summum',
    'supreme 29',
    'supreme dh',
    'surge',
    'sx trail',
    'tazer dh',
    'team dh',
    'ticket dj',
    'ticket s',
    'torque dhx',
    'torque frx',
    'tr450',
    'transition bottle rocket',
    'transition tr11',
    'transition tr450',
    'trek session',
    'trek ticket dj',
    'trek ticket s',
    'two15',
    'two50',
    'vitus dominer',
    'voltage fr',
    'voltage yz',
    'wildcard',
    'wilson',
    'wolf ridge pro',
    'wreckoning',
    'yt industries dirt love',
    'yt industries play',
    'yt industries tues',
    'zircus',
}
